# Generated by Django 3.1.1 on 2020-09-20 22:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200920_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 20, 22, 44, 47, 867748, tzinfo=utc)),
        ),
    ]
