# Generated by Django 3.1.1 on 2020-09-23 22:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200920_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 23, 22, 23, 12, 594122, tzinfo=utc)),
        ),
    ]
