# Generated by Django 3.1.1 on 2020-09-25 21:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200924_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 25, 21, 27, 33, 451800, tzinfo=utc)),
        ),
    ]
