# Generated by Django 3.1.1 on 2020-09-26 22:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200925_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 26, 22, 50, 28, 340291, tzinfo=utc)),
        ),
    ]
